### PR TITLE
Feature checklist

### PR DESCRIPTION
**Pull request by fvantienen**
This adds the option to add a checklist to your airframe which can be shown in the GCS. When an item is checked off or entered it is send to the on- and off board log.

An example checklist is:
```
    <checklist>
        <item name="pic" type="text">Enter the PIC</item>
        <item name="pac" type="text">Enter the PAC</item>
        <item name="gcs" type="text">Enter the GCS op</item>
        <item name="goal" type="text">Goal of the flight</item>
        <item name="basic law">Location, airspace and weather</item>
        <item name="RC Battery">Check the RC battery</item>
        <item name="tail connection">Check tail connection</item>
        <item name="wing tape">Check wings taped and secured</item>
        <item name="attitude">Check attitude and heading</item>
        <item name="takeoff location">Put UAV on take-off location</item>
        <item name="flight plan">Check flight plan</item>
        <item name="flight block">Switch to correct flight block</item>
        <item name="camera">Switch on camera</item>
        <item name="announce">Announce flight to other airspace users</item>
    </checklist>
```

Screenshot 2024-05-15 at 13 29 45

### CODE REVIEW

**Comment by fvantienen** [comment]
@Fabien-B I changed the chatbubble layout also, because this way it doesn't have as much whitespace as before.
Though what is still really missing is like a small icon showing that you have received a message when the chat is closed on the chatbubble widget icon.

This also combines messages when they are received shortly after each other:
Screenshot 2024-05-16 at 15 25 59

**Review by dewagter — APPROVED** [review]
Great update.

**Comment by fvantienen** [comment]
This also fixes #20

**Comment by fvantienen** [comment]
@Fabien-B can you check and merge this if you are ok?

**Comment by dewagter** [comment]
Works great for me.

**Comment by Fabien-B** [comment]
Nice addition!
Maybe it could be good to add a label in the checklist widget in the case there is no checklist in the airframe?
Something like 
```
No checklist found in airframe.
You may need to update the setting 'Checks->ground_done' manually.
```

**Pull request merged**
