### PR TITLE
Fix maximum value in sliders

### LINKED ISSUE #22: Wrong maximum value in sliders
https://github.com/paparazzi/PprzGCS/blob/2f801aeb96a5d61e5be912c8dbe5638a4c456d40/src/widgets/basics/double_slider.cpp#L23

As can be seen in the line above the maximum is calculated incorrectly for the sliders as `+1` is added. I think you wanted to `ceil` the value, which is probably the best to just do by calling `ceil`. Or else I think the correct solution is `(max - min + step-1) / step` if `step > 0` as by default the value is rounded down (`floor`).

### PR DESCRIPTION
**Pull request by fvantienen**
This should fix #22 (not tested)

### CODE REVIEW

**Comment by Fabien-B** [comment]
Are you sure ? I trust you but I would like it to be tested :smile: .
For me this is more a "fencepost" problem.
Lets take an example with `min=3, max=5, step=0.1`:
`ceil((5-3) / 0.1) = 20`
`(5-3) / 0.1 + 1 = 21`
```
>>> [3+0.1*i for i in range(21)]
[3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0]
```

In what situation did you had a problem ?
I would guess it's probably a rounding issue of the computed value.

**Comment by fvantienen** [comment]
The problem is with every setting that instead of the maximum value I can select 1 higher than the maximum. But I see where your calculation goes wrong it is in the next line `setRange(0, nb_steps);`.

If you take for example (min: 0, max: 4, step: 1)
Then you end up with `(4 - 0) / 1 + 1 = 5` as a value for `nb_steps`, which should have been correct. But since you set the range starting from `0` (in the `setRange`) you end up with 1 more in the range, as `0 -> 5` is actually 6 options. So my solution should be correct and ceiling is just a nice addition, but I didn't test compile it yet.

**Comment by Fabien-B** [comment]
Ok, the +1 was already accounted for !
Let me know when you tested it works as expected.

**Comment by fvantienen** [comment]
Tested and works

**Pull request merged**
